#!/usr/bin/env bash

#
# test_pci_mmio.sh
#
# Automated integration test for the sk_e1000 PCI/MMIO milestone.
#
# Author: Santosh Kumar
#
# Validates the functionality currently implemented in sk_e1000.c:
#
#   - Intel 82540EM PCI device exists
#   - PCI identity is 8086:100e
#   - custom sk_e1000 module loads
#   - sk_e1000 binds to the NIC
#   - BAR0 discovery succeeds
#   - CTRL register is read through MMIO
#   - STATUS register is read through MMIO
#   - probe completes successfully
#   - module unload calls remove()
#   - PCI device is released cleanly
#

set -euo pipefail


PCI_DEVICE="0000:00:04.0"

EXPECTED_VENDOR="0x8086"
EXPECTED_DEVICE="0x100e"

MODULE_NAME="sk_e1000"

#
# Module path can be supplied as argument 1.
#
# Example:
#
#   ./test_pci_mmio.sh ./sk_e1000.ko
#
MODULE_PATH="${1:-./sk_e1000.ko}"


pass()
{
    echo "[PASS] $1"
}


fail()
{
    echo "[FAIL] $1" >&2
    exit 1
}


echo
echo "========================================"
echo " sk_e1000 PCI/MMIO Integration Test"
echo "========================================"
echo


#
# TEST 1
# Verify that the expected PCI device exists.
#
SYSFS_DEVICE="/sys/bus/pci/devices/${PCI_DEVICE}"

if [[ ! -d "$SYSFS_DEVICE" ]]; then
    fail "PCI device ${PCI_DEVICE} not found"
fi

pass "PCI device ${PCI_DEVICE} exists"


#
# TEST 2
# Verify Vendor ID and Device ID.
#
vendor="$(cat "${SYSFS_DEVICE}/vendor")"
device="$(cat "${SYSFS_DEVICE}/device")"

if [[ "$vendor" != "$EXPECTED_VENDOR" ]]; then
    fail "Unexpected Vendor ID: ${vendor}"
fi

if [[ "$device" != "$EXPECTED_DEVICE" ]]; then
    fail "Unexpected Device ID: ${device}"
fi

pass "PCI identity is ${EXPECTED_VENDOR}:${EXPECTED_DEVICE}"


#
# TEST 3
# Verify the kernel module exists.
#
if [[ ! -f "$MODULE_PATH" ]]; then
    fail "Kernel module not found: ${MODULE_PATH}"
fi

pass "Kernel module exists"


#
# TEST 4
# If another driver currently owns the NIC, release it.
#
if [[ -L "${SYSFS_DEVICE}/driver" ]]; then

    current_driver="$(
        basename "$(readlink -f "${SYSFS_DEVICE}/driver")"
    )"

    echo "Current driver: ${current_driver}"

    if [[ "$current_driver" == "e1000" ]]; then

        echo "$PCI_DEVICE" |
            sudo tee /sys/bus/pci/drivers/e1000/unbind >/dev/null

        pass "Stock e1000 driver released"
    elif [[ "$current_driver" == "$MODULE_NAME" ]]; then

        sudo rmmod "$MODULE_NAME"

        pass "Previous sk_e1000 instance removed"
    else

        fail "Unexpected driver owns NIC: ${current_driver}"
    fi
fi


#
# Device should now be unclaimed.
#
if [[ -L "${SYSFS_DEVICE}/driver" ]]; then
    fail "PCI device is still owned by a driver"
fi

pass "PCI device available for test"


#
# Clear kernel log in this isolated development VM.
#
sudo dmesg -C


#
# TEST 5
# Load our custom driver.
#
sudo insmod "$MODULE_PATH"

pass "sk_e1000 module loaded"


#
# TEST 6
# Verify Linux bound sk_e1000 to the expected NIC.
#
if [[ ! -L "${SYSFS_DEVICE}/driver" ]]; then
    fail "No driver bound after insmod"
fi

bound_driver="$(
    basename "$(readlink -f "${SYSFS_DEVICE}/driver")"
)"

if [[ "$bound_driver" != "$MODULE_NAME" ]]; then
    fail "Unexpected bound driver: ${bound_driver}"
fi

pass "sk_e1000 owns ${PCI_DEVICE}"


#
# Capture messages generated by this test run.
#
kernel_log="$(sudo dmesg)"


#
# TEST 7
# Verify PCI match.
#
if ! grep -q \
    "sk_e1000: matched PCI device 8086:100e" \
    <<< "$kernel_log"; then

    fail "PCI device match log not found"
fi

pass "PCI ID match verified"


#
# TEST 8
# Verify BAR0 discovery.
#
if ! grep -q \
    "sk_e1000: BAR0 physical start=" \
    <<< "$kernel_log"; then

    fail "BAR0 discovery log not found"
fi

pass "BAR0 discovery verified"


#
# TEST 9
# Verify CTRL MMIO read.
#
if ! grep -q \
    "sk_e1000: CTRL   = 0x" \
    <<< "$kernel_log"; then

    fail "CTRL register MMIO read not found"
fi

pass "CTRL register MMIO read verified"


#
# TEST 10
# Verify STATUS MMIO read.
#
if ! grep -q \
    "sk_e1000: STATUS = 0x" \
    <<< "$kernel_log"; then

    fail "STATUS register MMIO read not found"
fi

pass "STATUS register MMIO read verified"


#
# TEST 11
# Verify probe reached its success point.
#
if ! grep -q \
    "sk_e1000: PCI/MMIO initialization PASSED" \
    <<< "$kernel_log"; then

    fail "PCI/MMIO initialization did not complete"
fi

pass "PCI/MMIO initialization completed"


#
# TEST 12
# Unload the driver.
#
sudo rmmod "$MODULE_NAME"

pass "sk_e1000 module unloaded"


#
# TEST 13
# Verify remove() completed.
#
if ! sudo dmesg |
    grep -q \
    "sk_e1000: device removed and resources released"; then

    fail "Driver cleanup message not found"
fi

pass "Driver cleanup verified"


#
# TEST 14
# Verify our driver no longer owns the device.
#
if [[ -L "${SYSFS_DEVICE}/driver" ]]; then

    remaining_driver="$(
        basename "$(readlink -f "${SYSFS_DEVICE}/driver")"
    )"

    if [[ "$remaining_driver" == "$MODULE_NAME" ]]; then
        fail "sk_e1000 still owns PCI device after rmmod"
    fi
fi

pass "PCI device released successfully"


echo
echo "========================================"
echo " ALL PCI/MMIO TESTS PASSED"
echo "========================================"
echo