/*
 * sk_e1000_logic.h
 *
 * Shared pure logic for the sk_e1000 driver.
 *
 * This interface contains hardware-independent decision logic that
 * is used by both the production kernel driver and user-space unit
 * tests.
 *
 * Author: Santosh Kumar
 */

#ifndef SK_E1000_LOGIC_H
#define SK_E1000_LOGIC_H


/*
 * The production driver is compiled inside the Linux kernel and uses
 * kernel integer types such as u32.
 *
 * User-space unit tests use the standard C fixed-width integer types.
 *
 * sk_e1000_u32 provides one common 32-bit type for both environments.
 */

#ifdef __KERNEL__

#include <linux/types.h>

typedef u32 sk_e1000_u32;

#else

#include <stdint.h>

typedef uint32_t sk_e1000_u32;

#endif


/*
 * --------------------------------------------------------------------------
 * INTERRUPT CAUSE BITS
 * --------------------------------------------------------------------------
 *
 * LSC = Link Status Change.
 *
 * Bit 2 in the Intel e1000 Interrupt Cause Register (ICR).
 *
 * The current bring-up milestone uses LSC to deterministically verify
 * that an interrupt travels through the complete device-to-driver
 * interrupt path.
 */

#define SK_E1000_INT_LSC    0x00000004U


/*
 * --------------------------------------------------------------------------
 * INTERRUPT DECISION LOGIC
 * --------------------------------------------------------------------------
 */

/*
 * Return non-zero when the Interrupt Cause Register reports at least
 * one pending interrupt cause.
 *
 * A zero ICR value is especially important for legacy shared INTx
 * handling because it means the interrupt was not generated by this
 * e1000 device.
 */
int sk_e1000_irq_is_pending(sk_e1000_u32 cause);


/*
 * Return non-zero when Link Status Change is one of the reported
 * interrupt causes.
 *
 * The function tests an individual bit rather than comparing the
 * complete ICR value because several interrupt causes can be reported
 * simultaneously.
 */
int sk_e1000_irq_has_lsc(sk_e1000_u32 cause);


#endif /* SK_E1000_LOGIC_H */